using UnityEngine;

namespace DataCenterPlus
{
    // ============================================================================
    //  DataCenterPlus — central tunable config.
    //  Everything a player/modder is likely to tweak lives here. Edit, rebuild,
    //  drop the new DLL in Mods/.  All values were chosen from in-game balance
    //  (see README) and can be freely changed.
    // ============================================================================
    internal static class TierConfig
    {
        // ---------------------------------------------------------------- SERVERS
        // The new "HPC" server tier is generated by cloning every existing server
        // and multiplying its IOPS (maxProcessingSpeed) by this factor.
        //   5000 IOPS (3U)  -> 25000     12000 IOPS (7U) -> 60000
        internal const float ServerIopsMultiplier  = 5f;
        internal const float ServerPriceMultiplier = 5f;

        // Suffix appended to the cloned server's display name (e.g. "System x HPC").
        internal const string ServerNameSuffix = " HPC";

        // Optional tint so high-tier servers are visually distinct in the rack.
        // NOTE: server bodies are colour-coded by type (System x/RISC/Mainframe/GPU),
        // so body-tinting is OFF by default (alpha 0) to preserve that meaning. The
        // HPC cue is delivered via the name suffix and a recoloured shop icon instead.
        internal static readonly Color ServerTint = new Color(1.0f, 0.55f, 0.0f, 0.0f);

        // Shop-icon accent for HPC servers (multiplies the base icon; keep it light so
        // the colour-coded server icon still reads through). Alpha 0 disables.
        internal static readonly Color ServerIconAccent = new Color(1.0f, 0.82f, 0.35f, 1.0f);

        // If a cloned server reports 0 IOPS in-game (i.e. the game computes the
        // value at runtime instead of serialising it on the prefab), set this to
        // true and fill in the absolute values below. Normally leave false.
        internal static readonly bool ServerUseAbsoluteIops = false;
        internal const float ServerAbsoluteIopsSmall = 25000f; // for 3U-class bases
        internal const float ServerAbsoluteIopsLarge = 60000f; // for 7U-class bases
        internal const float ServerSmallLargeSplit  = 8000f;   // base IOPS below this = "small"

        // ------------------------------------------------ NETWORKING EQUIPMENT TIERS
        // Each tier produces a Switch, a Router and a Firewall, cloned from the
        // game's top QSFP+ switch. SpeedGbps is informational/for labels; the real
        // link bandwidth is carried by the matching SFP transceiver below.
        internal static readonly NetTier[] NetTiers =
        {
            new NetTier("QSFP28 100G",  100f, 35000,  new Color(0.00f, 0.80f, 0.85f, 1f)), // teal
            new NetTier("QSFP-DD 400G", 400f, 135000, new Color(0.95f, 0.75f, 0.10f, 1f)), // gold
        };

        // --------------------------------------------- SFP TRANSCEIVERS ("cabling")
        // Inserting one of these into a cable sets the link's connectionSpeed.
        // Sold as individual modules (not boxed) so purchasing never depends on the
        // vanilla SFP-box flow. Colour is used for the shop-icon accent.
        internal static readonly SfpTier[] SfpTiers =
        {
            new SfpTier("QSFP28 Transceiver 100G",  100f, 2500, new Color(0.00f, 0.80f, 0.85f, 1f)),
            new SfpTier("QSFP-DD Transceiver 400G", 400f, 8000, new Color(0.95f, 0.75f, 0.10f, 1f)),
        };

        // ------------------------------------------------- FIBER CABLES (per tier)
        // Dedicated cable reel for each bandwidth tier (cloned from the fiber QSFP
        // cable). Label and price per tier; colour is taken from the SFP tier above.
        internal static readonly (string Label, int Price)[] CableTiers =
        {
            ("Cable fiber QSFP28 100G",  1200),
            ("Cable fiber QSFP-DD 400G", 3500),
        };

        // --------------------------------------------------------- SHOP PLACEMENT
        // Name of the shop sub-section to place custom items under (created by the
        // base game / other mods). Falls back to the main shop list if not found.
        internal const string ShopSectionName = "HL Mods";
    }

    internal sealed class NetTier
    {
        public readonly string Label;
        public readonly float  SpeedGbps;
        public readonly int    Price;
        public readonly Color  Color;
        public NetTier(string label, float speedGbps, int price, Color color)
        {
            Label = label; SpeedGbps = speedGbps; Price = price; Color = color;
        }
    }

    internal sealed class SfpTier
    {
        public readonly string Label;
        public readonly float  SpeedGbps;
        public readonly int    Price;
        public readonly Color  Color;
        public SfpTier(string label, float speedGbps, int price, Color color)
        {
            Label = label; SpeedGbps = speedGbps; Price = price; Color = color;
        }
    }
}
