using UnityEngine;

namespace DataCenterPlus
{
    // ============================================================================
    //  DataCenterPlus — central tunable config.
    //  Everything a player/modder is likely to tweak lives here. Edit, rebuild,
    //  drop the new DLL in Mods/.  All values were chosen from in-game balance
    //  (see README) and can be freely changed.
    // ============================================================================
    internal static class TierConfig
    {
        // ---------------------------------------------------------------- SERVERS
        // The new "HPC" server tier is generated by cloning every existing server
        // and multiplying its IOPS (maxProcessingSpeed) by this factor.
        //   5000 IOPS (3U)  -> 25000     12000 IOPS (7U) -> 60000
        internal const float ServerIopsMultiplier  = 5f;
        internal const float ServerPriceMultiplier = 5f;

        // Suffix appended to the cloned server's display name (e.g. "System x HPC").
        internal const string ServerNameSuffix = " HPC";

        // Optional tint so high-tier servers are visually distinct in the rack.
        // NOTE: server bodies are colour-coded by type (System x/RISC/Mainframe/GPU),
        // so body-tinting is OFF by default (alpha 0) to preserve that meaning. The
        // HPC cue is delivered via the name suffix and a recoloured shop icon instead.
        internal static readonly Color ServerTint = new Color(1.0f, 0.55f, 0.0f, 0.0f);

        // Shop-icon accent for HPC servers (multiplies the base icon; keep it light so
        // the colour-coded server icon still reads through). Alpha 0 disables.
        internal static readonly Color ServerIconAccent = new Color(1.0f, 0.82f, 0.35f, 1.0f);

        // If a cloned server reports 0 IOPS in-game (i.e. the game computes the
        // value at runtime instead of serialising it on the prefab), set this to
        // true and fill in the absolute values below. Normally leave false.
        internal static readonly bool ServerUseAbsoluteIops = false;
        internal const float ServerAbsoluteIopsSmall = 25000f; // for 3U-class bases
        internal const float ServerAbsoluteIopsLarge = 60000f; // for 7U-class bases
        internal const float ServerSmallLargeSplit  = 8000f;   // base IOPS below this = "small"

        // ------------------------------------------------ NETWORKING EQUIPMENT TIERS
        // Each tier produces a Switch, a Router and a Firewall, cloned from the
        // game's top QSFP+ switch. SpeedGbps is informational/for labels; the real
        // link bandwidth is carried by the matching SFP transceiver below.
        internal static readonly NetTier[] NetTiers =
        {
            new NetTier("QSFP28 100G",  100f, 35000,  new Color(0.00f, 0.80f, 0.85f, 1f)), // teal
            new NetTier("QSFP-DD 400G", 400f, 135000, new Color(0.95f, 0.75f, 0.10f, 1f)), // gold
        };

        // --------------------------------------------- SFP TRANSCEIVERS ("cabling")
        // Inserting one of these into a cable sets the link's connectionSpeed.
        // Sold as individual modules (not boxed) so purchasing never depends on the
        // vanilla SFP-box flow. Colour is used for the shop-icon accent.
        internal static readonly SfpTier[] SfpTiers =
        {
            new SfpTier("QSFP28 Transceiver 100G",  100f, 2500, new Color(0.00f, 0.80f, 0.85f, 1f)),
            new SfpTier("QSFP-DD Transceiver 400G", 400f, 8000, new Color(0.95f, 0.75f, 0.10f, 1f)),
        };

        // ------------------------------------------------- FIBER CABLES (per tier)
        // Dedicated cable reel for each bandwidth tier (cloned from the fiber QSFP
        // cable). Label and price per tier; colour is taken from the SFP tier above.
        internal static readonly (string Label, int Price)[] CableTiers =
        {
            ("Cable fiber QSFP28 100G",  1200),
            ("Cable fiber QSFP-DD 400G", 3500),
        };

        // ----------------------------------------------- PORT / COMPATIBILITY TUNING
        // The game gates SFP insertion by integer type match (sfpTypeSupported == sfpType)
        // AND derives cable compatibility + port speed from that same type via native
        // tables. Custom type IDs break those native lookups (0/0 speed, "wrong cable").
        // So we keep the native QSFP type on our modules/ports (realistic: 100G QSFP28
        // shares the QSFP form factor) and differentiate tiers by speed + name instead.
        // Set true only to experiment with hard type exclusivity.
        internal const bool MatchDevicePortsToTier = false;

        // New high-IOPS servers clone a base server, whose onboard ports are low-speed.
        // When true, the server's ports are bumped so the extra IOPS can actually flow.
        // Leave the type at -1 to keep the port's SFP type and only raise its speed.
        internal const bool  ApplyServerPortSpeed = true;
        internal const float ServerPortSpeedGbps  = 25f;   // onboard port speed for HPC servers
        internal const int   ServerPortSfpType    = -1;    // -1 = don't change port SFP type

        // The game stores port speed as (displayed Gbps ÷ 5): e.g. a 1 GbE port has
        // connectionSpeed 0.2, a 100 Gbps fibre patch-panel port has 20. All our Gbps
        // values are divided by this before being written to connectionSpeed.
        internal const float SpeedDivisor = 5f;

        // Verbose diagnostics (port dumps, candidate lists, hover/insert logs). Off for
        // release; set true to troubleshoot. The concise startup summary always logs.
        internal static readonly bool LogPortDetails = false;

        // Vanilla patch panels cap each port at ~100 Gbps, which bottlenecks 400G links.
        // When true, every patch panel's ports have their rated speed raised on placement.
        internal static readonly bool  RaisePatchPanelCap   = true;
        internal const float PatchPanelPortSpeedGbps = 400f;

        // ------------------------------------------------ DISPATCH-ALL TECHNICIAN BUTTON
        // Adds a "Send Tech: All" button to the Asset Management screen that sends a
        // technician to every device needing one (EOL and/or broken) in one click —
        // instead of clicking thousands individually. Already-assigned devices are
        // skipped; the game still charges the per-technician cost and queues the jobs.
        // The game's existing "add all broken to queue" button is also extended to EOL.
        internal const bool DispatchIncludeEol    = true;   // devices at end-of-life (eolTime <= 0)
        internal const bool DispatchIncludeBroken = true;   // broken devices (isBroken)
        internal const bool DispatchIncludeWarningSigns = true; // devices showing a warning/error sign
        internal static readonly string DispatchButtonLabel = "Send Tech: All";
        // Position offset (pixels) of the injected button from the screen's Return button.
        internal static readonly Vector2 DispatchButtonOffset = new Vector2(0f, 70f);

        // ------------------------------------------------ CABLE UNPLUG HOLD-TIME
        // Unplugging a cable is a hold-to-interact "second action" (~2-3s by default).
        // This scales the hold time on every cable so bulk unplugging is less tedious.
        // 1.0 = vanilla, 0.25 = quarter the time, 0 = effectively instant. The field(s)
        // are detected per-cable; set LogPortDetails=true to log the original values.
        internal static readonly bool  ReduceCableUnplugHold = true;
        internal const float CableUnplugHoldMultiplier = 0.25f;





        internal const string ShopSectionName = "HL Mods";
    }

    internal sealed class NetTier
    {
        public readonly string Label;
        public readonly float  SpeedGbps;
        public readonly int    Price;
        public readonly Color  Color;
        public NetTier(string label, float speedGbps, int price, Color color)
        {
            Label = label; SpeedGbps = speedGbps; Price = price; Color = color;
        }
    }

    internal sealed class SfpTier
    {
        public readonly string Label;
        public readonly float  SpeedGbps;
        public readonly int    Price;
        public readonly Color  Color;
        public SfpTier(string label, float speedGbps, int price, Color color)
        {
            Label = label; SpeedGbps = speedGbps; Price = price; Color = color;
        }
    }
}
